/// <reference types="cypress" />

describe("Profile Page Seeting", ()=> {
    beforeEach(() => { 
        cy.visit("https://8wc5wa.capedia.work/")
    })

     it("Basic Info", () => {
        cy.contains("Sign In").click()
        cy.get("#id_login").type("coachaccc@gmail.com")
        cy.get("#id_password").type("Reds123!")
        cy.contains("Login").click()
        cy.contains("Coach01").should("be.visible")
        cy.contains("Profile Page Setting").click()
        cy.get("#id_display_name").clear()
        cy.get("#id_display_name").type("Number 1 Account")
        cy.get("#id_title").clear()
        cy.get("#id_title").type("advance python")
        cy.get("#id_specialism_0").check({force:true})
        cy.get("#id_city").select("1")
        cy.get("#id_country").select("1")
        cy.get("#id_certification_0").uncheck({force:true})
        cy.get("#id_certification_1").uncheck({force:true})
        cy.get("#id_certification_4").check({force:true})
        //cy.get(".custom-control-label mb-0")
        //cy.get("#submit-id-submit").click()
     })

     it("Profile Details", () =>{
        cy.contains("Sign In").click()
        cy.get("#id_login").type("coachaccc@gmail.com")
        cy.get("#id_password").type("Reds123!")
        cy.contains("Login").click()
        cy.contains("Coach01").should("be.visible")
        cy.contains("Profile Page Setting").click()
        cy.contains("Profile details").click()
        cy.get("#id_quote").clear()
        cy.get("#id_quote").type("i am coach that has been teaching for more than 20 year")
        cy.get("#id_bio_data").clear()
        cy.get("#id_bio_data").type("i am super experiance that even idiot can learny in minuts")
        cy.get("#id_people_coached").clear()
        cy.get("#id_people_coached").type("20")
        cy.get("#id_years_experience").clear()
        cy.get("#id_years_experience").type("20")
        cy.get("#id_video_uri").clear()
        cy.get("#id_video_uri").type("https://www.youtube.com/watch?v=uUvp0XgE--s")
        cy.get("#id_video_title").clear()
        cy.get("#id_video_title").type("THe awesomeoness of me")
        //cy.get("#submit-id-submit").click()
     })

     it("Testimonies", () => {
        cy.contains("Sign In").click()
        cy.get("#id_login").type("coachaccc@gmail.com")
        cy.get("#id_password").type("Reds123!")
        cy.contains("Login").click()
        cy.contains("Coach01").should("be.visible")
        cy.contains("Profile Page Setting").click()
        cy.contains("Testimonial").click()
        cy.get("#id_form-0-testimonial").clear()
        cy.get("#id_form-0-testimonial"). type("This guys so experience even idiot like me able to understand it clearly")
        cy.get("#id_form-0-given_by").clear()
        cy.get("#id_form-0-given_by").type("Jhon Wick")
        cy.get("#id_form-0-company_name").clear()
        cy.get("#id_form-0-company_name").type("Redsquare Software")
        cy.get("#id_form-0-title").clear()
        cy.get("#id_form-0-title").type("CEO")
     })

     it("Feature Course", () => {
      cy.contains("Sign In").click()
      cy.get("#id_login").type("coachaccc@gmail.com")
      cy.get("#id_password").type("Reds123!")
      cy.contains("Login").click()
      cy.contains("Coach01").should("be.visible")
      cy.contains("Profile Page Setting").click()
      cy.contains("Featured Course").click()
      cy.get("#id_featured_one").select("Cypress Crashcourse")
      //cy.contains("Cypress Crashcourse").click()
      cy.get("#id_featured_two").select("Youtube channel tutorial")
      //cy.contains("Youtube channel tutorial").click()
      cy.contains("Save").click({force:true})
     })
})